### ISSUE TITLE
Link to Curseforge broken

### ISSUE THREAD

**Issue by adriaan1313** [tempestsbox/tempestsbox.github.io#2]
on the site, it links to [https://curseforge.com/minecraft/customization/ttb](https://curseforge.com/minecraft/customization/ttb), but it doesn't work

**Comment by dvitski** [comment]
That's because it doesn't exist yet :p

**Comment by adriaan1313** [comment]
then why is it there

**Comment by dvitski** [comment]
It's a work-in-progress site, as is the pack - it's there for release
